// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: proto/repeated_scalarts.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepeatedScalarHolder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*RepeatedScalarsItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RepeatedScalarHolder) Reset() {
	*x = RepeatedScalarHolder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repeated_scalarts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedScalarHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedScalarHolder) ProtoMessage() {}

func (x *RepeatedScalarHolder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repeated_scalarts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedScalarHolder.ProtoReflect.Descriptor instead.
func (*RepeatedScalarHolder) Descriptor() ([]byte, []int) {
	return file_proto_repeated_scalarts_proto_rawDescGZIP(), []int{0}
}

func (x *RepeatedScalarHolder) GetItems() []*RepeatedScalarsItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RepeatedScalarsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int32S  []int32   `protobuf:"varint,1,rep,packed,name=int32s,proto3" json:"int32s,omitempty"`
	Int64S  []int64   `protobuf:"varint,2,rep,packed,name=int64s,proto3" json:"int64s,omitempty"`
	Uint32S []uint32  `protobuf:"varint,3,rep,packed,name=uint32s,proto3" json:"uint32s,omitempty"`
	Uint64S []uint64  `protobuf:"varint,4,rep,packed,name=uint64s,proto3" json:"uint64s,omitempty"`
	Floats  []float32 `protobuf:"fixed32,5,rep,packed,name=floats,proto3" json:"floats,omitempty"`
	Strings []string  `protobuf:"bytes,6,rep,name=strings,proto3" json:"strings,omitempty"`
	Bools   []bool    `protobuf:"varint,7,rep,packed,name=bools,proto3" json:"bools,omitempty"`
	Bytes   []byte    `protobuf:"bytes,8,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *RepeatedScalarsItem) Reset() {
	*x = RepeatedScalarsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repeated_scalarts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedScalarsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedScalarsItem) ProtoMessage() {}

func (x *RepeatedScalarsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repeated_scalarts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedScalarsItem.ProtoReflect.Descriptor instead.
func (*RepeatedScalarsItem) Descriptor() ([]byte, []int) {
	return file_proto_repeated_scalarts_proto_rawDescGZIP(), []int{1}
}

func (x *RepeatedScalarsItem) GetInt32S() []int32 {
	if x != nil {
		return x.Int32S
	}
	return nil
}

func (x *RepeatedScalarsItem) GetInt64S() []int64 {
	if x != nil {
		return x.Int64S
	}
	return nil
}

func (x *RepeatedScalarsItem) GetUint32S() []uint32 {
	if x != nil {
		return x.Uint32S
	}
	return nil
}

func (x *RepeatedScalarsItem) GetUint64S() []uint64 {
	if x != nil {
		return x.Uint64S
	}
	return nil
}

func (x *RepeatedScalarsItem) GetFloats() []float32 {
	if x != nil {
		return x.Floats
	}
	return nil
}

func (x *RepeatedScalarsItem) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *RepeatedScalarsItem) GetBools() []bool {
	if x != nil {
		return x.Bools
	}
	return nil
}

func (x *RepeatedScalarsItem) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_proto_repeated_scalarts_proto protoreflect.FileDescriptor

var file_proto_repeated_scalarts_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x4d, 0x0a, 0x14, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x48, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xd7, 0x01, 0x0a, 0x13, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x73, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6c,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x6f, 0x73, 0x64, 0x72, 0x76, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_repeated_scalarts_proto_rawDescOnce sync.Once
	file_proto_repeated_scalarts_proto_rawDescData = file_proto_repeated_scalarts_proto_rawDesc
)

func file_proto_repeated_scalarts_proto_rawDescGZIP() []byte {
	file_proto_repeated_scalarts_proto_rawDescOnce.Do(func() {
		file_proto_repeated_scalarts_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_repeated_scalarts_proto_rawDescData)
	})
	return file_proto_repeated_scalarts_proto_rawDescData
}

var file_proto_repeated_scalarts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_repeated_scalarts_proto_goTypes = []interface{}{
	(*RepeatedScalarHolder)(nil), // 0: protoquery.RepeatedScalarHolder
	(*RepeatedScalarsItem)(nil),  // 1: protoquery.RepeatedScalarsItem
}
var file_proto_repeated_scalarts_proto_depIdxs = []int32{
	1, // 0: protoquery.RepeatedScalarHolder.items:type_name -> protoquery.RepeatedScalarsItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_repeated_scalarts_proto_init() }
func file_proto_repeated_scalarts_proto_init() {
	if File_proto_repeated_scalarts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_repeated_scalarts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedScalarHolder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repeated_scalarts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedScalarsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_repeated_scalarts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_repeated_scalarts_proto_goTypes,
		DependencyIndexes: file_proto_repeated_scalarts_proto_depIdxs,
		MessageInfos:      file_proto_repeated_scalarts_proto_msgTypes,
	}.Build()
	File_proto_repeated_scalarts_proto = out.File
	file_proto_repeated_scalarts_proto_rawDesc = nil
	file_proto_repeated_scalarts_proto_goTypes = nil
	file_proto_repeated_scalarts_proto_depIdxs = nil
}
