// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: proto/message_with_enum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageWithEnum_Enum int32

const (
	MessageWithEnum_ENUM1 MessageWithEnum_Enum = 0
	MessageWithEnum_ENUM2 MessageWithEnum_Enum = 1
	MessageWithEnum_ENUM3 MessageWithEnum_Enum = 2
)

// Enum value maps for MessageWithEnum_Enum.
var (
	MessageWithEnum_Enum_name = map[int32]string{
		0: "ENUM1",
		1: "ENUM2",
		2: "ENUM3",
	}
	MessageWithEnum_Enum_value = map[string]int32{
		"ENUM1": 0,
		"ENUM2": 1,
		"ENUM3": 2,
	}
)

func (x MessageWithEnum_Enum) Enum() *MessageWithEnum_Enum {
	p := new(MessageWithEnum_Enum)
	*p = x
	return p
}

func (x MessageWithEnum_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageWithEnum_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_with_enum_proto_enumTypes[0].Descriptor()
}

func (MessageWithEnum_Enum) Type() protoreflect.EnumType {
	return &file_proto_message_with_enum_proto_enumTypes[0]
}

func (x MessageWithEnum_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageWithEnum_Enum.Descriptor instead.
func (MessageWithEnum_Enum) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_with_enum_proto_rawDescGZIP(), []int{1, 0}
}

type MessageWithAllowAliasEnum_Enum int32

const (
	MessageWithAllowAliasEnum_ENUM1       MessageWithAllowAliasEnum_Enum = 0
	MessageWithAllowAliasEnum_ENUM2       MessageWithAllowAliasEnum_Enum = 1
	MessageWithAllowAliasEnum_ALIAS_ENUM2 MessageWithAllowAliasEnum_Enum = 1
	MessageWithAllowAliasEnum_ENUM3       MessageWithAllowAliasEnum_Enum = 2
)

// Enum value maps for MessageWithAllowAliasEnum_Enum.
var (
	MessageWithAllowAliasEnum_Enum_name = map[int32]string{
		0: "ENUM1",
		1: "ENUM2",
		// Duplicate value: 1: "ALIAS_ENUM2",
		2: "ENUM3",
	}
	MessageWithAllowAliasEnum_Enum_value = map[string]int32{
		"ENUM1":       0,
		"ENUM2":       1,
		"ALIAS_ENUM2": 1,
		"ENUM3":       2,
	}
)

func (x MessageWithAllowAliasEnum_Enum) Enum() *MessageWithAllowAliasEnum_Enum {
	p := new(MessageWithAllowAliasEnum_Enum)
	*p = x
	return p
}

func (x MessageWithAllowAliasEnum_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageWithAllowAliasEnum_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_with_enum_proto_enumTypes[1].Descriptor()
}

func (MessageWithAllowAliasEnum_Enum) Type() protoreflect.EnumType {
	return &file_proto_message_with_enum_proto_enumTypes[1]
}

func (x MessageWithAllowAliasEnum_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageWithAllowAliasEnum_Enum.Descriptor instead.
func (MessageWithAllowAliasEnum_Enum) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_with_enum_proto_rawDescGZIP(), []int{2, 0}
}

type MessageWithEnumHolder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages          []*MessageWithEnum           `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	MessagesWithAlias []*MessageWithAllowAliasEnum `protobuf:"bytes,2,rep,name=messages_with_alias,json=messagesWithAlias,proto3" json:"messages_with_alias,omitempty"`
}

func (x *MessageWithEnumHolder) Reset() {
	*x = MessageWithEnumHolder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_message_with_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithEnumHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithEnumHolder) ProtoMessage() {}

func (x *MessageWithEnumHolder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_with_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithEnumHolder.ProtoReflect.Descriptor instead.
func (*MessageWithEnumHolder) Descriptor() ([]byte, []int) {
	return file_proto_message_with_enum_proto_rawDescGZIP(), []int{0}
}

func (x *MessageWithEnumHolder) GetMessages() []*MessageWithEnum {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *MessageWithEnumHolder) GetMessagesWithAlias() []*MessageWithAllowAliasEnum {
	if x != nil {
		return x.MessagesWithAlias
	}
	return nil
}

type MessageWithEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnumField   MessageWithEnum_Enum `protobuf:"varint,1,opt,name=enum_field,json=enumField,proto3,enum=protoquery.MessageWithEnum_Enum" json:"enum_field,omitempty"`
	StringField string               `protobuf:"bytes,2,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
}

func (x *MessageWithEnum) Reset() {
	*x = MessageWithEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_message_with_enum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithEnum) ProtoMessage() {}

func (x *MessageWithEnum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_with_enum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithEnum.ProtoReflect.Descriptor instead.
func (*MessageWithEnum) Descriptor() ([]byte, []int) {
	return file_proto_message_with_enum_proto_rawDescGZIP(), []int{1}
}

func (x *MessageWithEnum) GetEnumField() MessageWithEnum_Enum {
	if x != nil {
		return x.EnumField
	}
	return MessageWithEnum_ENUM1
}

func (x *MessageWithEnum) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

type MessageWithAllowAliasEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnumField   MessageWithAllowAliasEnum_Enum `protobuf:"varint,1,opt,name=enum_field,json=enumField,proto3,enum=protoquery.MessageWithAllowAliasEnum_Enum" json:"enum_field,omitempty"`
	StringField string                         `protobuf:"bytes,2,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
}

func (x *MessageWithAllowAliasEnum) Reset() {
	*x = MessageWithAllowAliasEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_message_with_enum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithAllowAliasEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithAllowAliasEnum) ProtoMessage() {}

func (x *MessageWithAllowAliasEnum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_with_enum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithAllowAliasEnum.ProtoReflect.Descriptor instead.
func (*MessageWithAllowAliasEnum) Descriptor() ([]byte, []int) {
	return file_proto_message_with_enum_proto_rawDescGZIP(), []int{2}
}

func (x *MessageWithAllowAliasEnum) GetEnumField() MessageWithAllowAliasEnum_Enum {
	if x != nil {
		return x.EnumField
	}
	return MessageWithAllowAliasEnum_ENUM1
}

func (x *MessageWithAllowAliasEnum) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

var File_proto_message_with_enum_proto protoreflect.FileDescriptor

var file_proto_message_with_enum_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x77, 0x69, 0x74, 0x68, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0xa7, 0x01, 0x0a, 0x15,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6e, 0x75, 0x6d, 0x48,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x55,
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x57, 0x69, 0x74, 0x68,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x3f, 0x0a, 0x0a, 0x65, 0x6e, 0x75,
	0x6d, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52,
	0x09, 0x65, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x27, 0x0a,
	0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x55, 0x4d, 0x31, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x4e, 0x55, 0x4d, 0x33, 0x10, 0x02, 0x22, 0xc7, 0x01, 0x0a, 0x19, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x49, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x22, 0x3c, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e,
	0x55, 0x4d, 0x31, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x4c, 0x49, 0x41, 0x53, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x55, 0x4d, 0x33, 0x10, 0x02, 0x1a, 0x02, 0x10, 0x01,
	0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x73, 0x64, 0x72, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_message_with_enum_proto_rawDescOnce sync.Once
	file_proto_message_with_enum_proto_rawDescData = file_proto_message_with_enum_proto_rawDesc
)

func file_proto_message_with_enum_proto_rawDescGZIP() []byte {
	file_proto_message_with_enum_proto_rawDescOnce.Do(func() {
		file_proto_message_with_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_message_with_enum_proto_rawDescData)
	})
	return file_proto_message_with_enum_proto_rawDescData
}

var file_proto_message_with_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_message_with_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_message_with_enum_proto_goTypes = []interface{}{
	(MessageWithEnum_Enum)(0),           // 0: protoquery.MessageWithEnum.Enum
	(MessageWithAllowAliasEnum_Enum)(0), // 1: protoquery.MessageWithAllowAliasEnum.Enum
	(*MessageWithEnumHolder)(nil),       // 2: protoquery.MessageWithEnumHolder
	(*MessageWithEnum)(nil),             // 3: protoquery.MessageWithEnum
	(*MessageWithAllowAliasEnum)(nil),   // 4: protoquery.MessageWithAllowAliasEnum
}
var file_proto_message_with_enum_proto_depIdxs = []int32{
	3, // 0: protoquery.MessageWithEnumHolder.messages:type_name -> protoquery.MessageWithEnum
	4, // 1: protoquery.MessageWithEnumHolder.messages_with_alias:type_name -> protoquery.MessageWithAllowAliasEnum
	0, // 2: protoquery.MessageWithEnum.enum_field:type_name -> protoquery.MessageWithEnum.Enum
	1, // 3: protoquery.MessageWithAllowAliasEnum.enum_field:type_name -> protoquery.MessageWithAllowAliasEnum.Enum
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_message_with_enum_proto_init() }
func file_proto_message_with_enum_proto_init() {
	if File_proto_message_with_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_message_with_enum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithEnumHolder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_message_with_enum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_message_with_enum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithAllowAliasEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_message_with_enum_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_with_enum_proto_goTypes,
		DependencyIndexes: file_proto_message_with_enum_proto_depIdxs,
		EnumInfos:         file_proto_message_with_enum_proto_enumTypes,
		MessageInfos:      file_proto_message_with_enum_proto_msgTypes,
	}.Build()
	File_proto_message_with_enum_proto = out.File
	file_proto_message_with_enum_proto_rawDesc = nil
	file_proto_message_with_enum_proto_goTypes = nil
	file_proto_message_with_enum_proto_depIdxs = nil
}
